apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '10'
    eks.amazonaws.com/role-arn: arn:aws:iam::126827061464:role/crossplane-bbkubes-1
  labels:
    app: crossplane-provider-terraform
  name: terraform-config
spec:
  serviceAccountName: crossplane-provider-terraform-bbkubes-1
  args:
  - -d
  - --poll=4m
  envFrom:
  - secretRef:
      name: crossplane-secrets
