apiVersion: eks.aws.upbound.io/v1beta1
kind: ClusterAuth
metadata:
  name: example-dev
spec:
  forProvider:
    clusterName: dooobar
    region: us-east-2
  providerConfigRef:
    name: provider-aws-eks
  writeConnectionSecretToRef:
    name: example-dev-cluster-conn
    namespace: crossplane-system
# ---
# apiVersion: kubernetes.crossplane.io/v1alpha1
# kind: ProviderConfig
# metadata:
#   name: example-workload-cluster
# spec:
#   credentials:
#     source: Secret
#     secretRef:
#       namespace: crossplane-system
#       name: example-dev-cluster-conn
#       key: kubeconfig
# ---
# apiVersion: kubernetes.crossplane.io/v1alpha2
# kind: Object
# metadata:
#   name: dev-namespace
# spec:
#   forProvider:
#     manifest:
#       apiVersion: v1
#       kind: Namespace
#       metadata:
#         name: crossplane-poc-from-poc-cluster
#   providerConfigRef:
#     name: example-workload-cluster
