apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chartmuseum
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://chartmuseum.github.io/charts
    targetRevision: 3.9.3
    helm:
      values: |-
        serviceAccount:
          create: true
          name: chartmuseum
          annotations:
            eks.amazonaws.com/role-arn: 'arn:aws:iam::126827061464:role/chartmuseum-bbkubes-1'
        env:
          open:
            AUTH_ANONYMOUS_GET: true
            AWS_SDK_LOAD_CONFIG: true
            STORAGE: amazon
            STORAGE_AMAZON_BUCKET: k1-artifacts-bbkubes-1-juyu2c
            STORAGE_AMAZON_PREFIX: kubefirst-charts
            STORAGE_AMAZON_REGION: us-east-2
            DISABLE_API: false
          existingSecret: chartmuseum-secrets
          existingSecretMappings:
            BASIC_AUTH_USER: BASIC_AUTH_USER
            BASIC_AUTH_PASS: BASIC_AUTH_PASS
        ingress:
          enabled: true
          pathType: "Prefix"
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            
            
            
          hosts:
            - name: chartmuseum.kubefist.com
              path: /
              tls: true
              tlsSecret: chartmuseum-tls
          ingressClassName: nginx
    chart: chartmuseum
  destination: 
    server: https://kubernetes.default.svc
    namespace: chartmuseum
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
