apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: default
  source:
    repoURL: git@github.com:barbekubes-com/gitops.git
    path: registry/clusters/bbkubes-1/components/ingress-nginx
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
